import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'cafe-1kg',
    name: 'Café Touba - 1kg',
    description: 'Un kilogramme de notre café Touba artisanal, pour les vrais amateurs.',
    price: 6500,
    image: 'https://placehold.co/400x400.png',
    slug: 'cafe-touba-1kg',
    category: 'Café Touba',
  },
  {
    id: 'cafe-500g',
    name: 'Café Touba - 500g',
    description: 'Un demi-kilo de pur plaisir, parfait pour une consommation régulière.',
    price: 3250,
    image: 'https://placehold.co/400x400.png',
    slug: 'cafe-touba-500g',
    category: 'Café Touba',
  },
  {
    id: 'cafe-250g',
    name: 'Café Touba - 250g',
    description: 'Le format idéal pour découvrir notre café ou pour un cadeau.',
    price: 2300,
    image: 'https://placehold.co/400x400.png',
    slug: 'cafe-touba-250g',
    category: 'Café Touba',
  },
  {
    id: 'cafe-125g',
    name: 'Café Touba - 125g',
    description: 'Une petite quantité pour une dégustation ou pour vos voyages.',
    price: 1150,
    image: 'https://placehold.co/400x400.png',
    slug: 'cafe-touba-125g',
    category: 'Café Touba',
  },
   {
    id: 'cafe-75g',
    name: 'Café Touba - 75g',
    description: 'Le format poche pour un café de qualité partout où vous allez.',
    price: 650,
    image: 'https://placehold.co/400x400.png',
    slug: 'cafe-touba-75g',
    category: 'Café Touba',
  },
  {
    id: 'pack-250g-12',
    name: 'Pack de 12 (250g)',
    description: 'Un pack économique de 12 sachets de 250g pour ne jamais en manquer.',
    price: 27600,
    image: 'https://placehold.co/400x400.png',
    slug: 'pack-de-12-250g',
    category: 'Café Touba',
  },
  {
    id: 'pack-125g-12',
    name: 'Pack de 12 (125g)',
    description: 'Un pack économique de 12 sachets de 125g, pratique et malin.',
    price: 13800,
    image: 'https://placehold.co/400x400.png',
    slug: 'pack-de-12-125g',
    category: 'Café Touba',
  },
    {
    id: 'pack-75g-12',
    name: 'Pack de 12 (75g)',
    description: 'Un pack économique de 12 sachets de 75g pour les petites faims.',
    price: 7800,
    image: 'https://placehold.co/400x400.png',
    slug: 'pack-de-12-75g',
    category: 'Café Touba',
  },
];
